

# learning_rate: [0.01,0.005,0.001,0.0005,0.0001]
# embedding_size: [64,128,256,512]  
learning_rate: [0.005]
embedding_size: [64]
depth: [5]
num_envs: [25]
dropout: 0.1 
e_layers: [1]
d_layers: 1
enc_in: 1
dec_in: 1
c_out: 1
embedd: timeF
use_multimodal: True
text_emb_dim: 768
beta1: 0.2

vq_weight: [0]
hyper_parameters: ["learning_rate","vq_weight","num_envs","embedding_size","depth"]
