factor: 3
learning_rate: [0.0005,0.0001,0.00005]
# d_model: 32
# d_ff: 32
embedding_size: 768
enc_in: 1
dec_in: 1
c_out: 1
itr: 1
use_multimodal : False
inverse : False

# Additional parameters that might be useful
patch_size: 4
stride: 2
add_prompt: 1
prompt_length: 4
sim_coef: -0.05
pool_size: 1000
percent: 100
trend_length: 4
seasonal_length: 4
llm_layers: 32
hyper_parameters: ["learning_rate"]

# best record
# Bitcoin
# Miss

#  Electricity
#  30 Jul 20:06    INFO    Parameters: ['seed', 'learning_rate']=(2025, 0.0005),
# Test: MAE: 0.1109    MSE: 0.0267    RMSE: 0.1634    MAPE: 0.4273    MSPE: 232.1456    

# FNSPID
# 30 Jul 20:49    INFO    Parameters: ['seed', 'learning_rate']=(2025, 5e-05),
# Test: MAE: 0.0176    MSE: 0.0017    RMSE: 0.0413    MAPE: 0.2653    MSPE: 24.6469    

# Env
# 30 Jul 19:48    INFO    Parameters: ['seed', 'learning_rate']=(2025, 0.0005),
# Test: MAE: 0.4428    MSE: 0.4149    RMSE: 0.6441    MAPE: 2.4397    MSPE: 328.0291    