

learning_rate: [0.005,0.001,0.0001,0.0005]

requires_news_embedding: false
use_news_embedding: false 
embedding_size: 512


depth: 10 
num_envs: 10
# num_envs: [10]

dropout: 0.1
meta_drop: 0.1
sudden_drop: 0.1
fuse_drop: 0.1

e_layers: 1
d_layers: 1
factor: 3
enc_in: 1
dec_in: 1
c_out: 1
embedd: timeF
use_multimodal: False
inverse: False
text_emb_dim: 4096
hyper_parameters: ["learning_rate"]
