train_file: "/train.json"
vali_file: "/vali.json"
test_file: "/test.json"
seq_len: 4
pred_len: 4
label_len: 0
batch_size: 16
patch_len: 2
stride: 1
enc_in: 1
inverse: False

#ver0 news和md
train_news_file: "/ver0/llama_embeddings/train_news.npy"
vali_news_file: "/ver0/llama_embeddings/vali_news.npy"
test_news_file: "/ver0/llama_embeddings/test_news.npy"
train_meta_file: "/ver0/llama_embeddings/train_meta_domain.npy"
vali_meta_file: "/ver0/llama_embeddings/vali_meta_domain.npy"
test_meta_file: "/ver0/llama_embeddings/test_meta_domain.npy"

#ver1 news和md
# train_news_file: "/ver1/llama_embeddings/train_news_ver1.npy"
# vali_news_file: "/ver1/llama_embeddings/vali_news_ver1.npy"
# test_news_file: "/ver1/llama_embeddings/test_news_ver1.npy"
# train_meta_file: "/ver1/llama_embeddings/train_meta_domain_ver1.npy"
# vali_meta_file: "/ver1/llama_embeddings/vali_meta_domain_ver1.npy"
# test_meta_file: "/ver1/llama_embeddings/test_meta_domain_ver1.npy"

content: "Traffic volome a crucial indicator in the VMT long-term deployment.'"
hyper_parameters: []